module.exports.positions = [
  {
    name: "EVEREADY",
    desc: "Eveready Industries India Limited",
    product: "CNC",
    qty: 2,
    avg: 316.27,
    ltp: 312.35,
    pl: 0.58,
    type: "positive",
  },
  {
    name: "JUBLFOOD",
    desc: "Jubilant Foodworks Limited",
    product: "CNC",
    qty: 1,
    avg: 3124.75,
    ltp: 3082.65,
    pl: 10.04,
    type: "positive",
  },
  {
    name: "INFY",
    desc: "Infosys Limited",
    product: "MIS",
    qty: 10,
    avg: 1550.00,
    ltp: 1555.45,
    pl: 54.50,
    type: "positive",
  },
  {
    name: "TCS",
    desc: "Tata Consultancy Services",
    product: "CNC",
    qty: 5,
    avg: 3210.00,
    ltp: 3194.80,
    pl: -76.00,
    type: "negative",
  },
  {
    name: "RELIANCE",
    desc: "Reliance Industries Limited",
    product: "MIS",
    qty: 8,
    avg: 2085.50,
    ltp: 2112.40,
    pl: 215.20,
    type: "positive",
  },
];