module.exports.watchlist = [
  {
    id: 1,
    name: "INFY",
    exchange: "NSE",
    price: 1555.45,
    percent: -1.60,
    isDown: true,
  },
  {
    id: 2,
    name: "ONGC",
    exchange: "NSE",
    price: 116.8,
    percent: -0.09,
    isDown: true,
  },
  {
    id: 3,
    name: "TCS",
    exchange: "NSE",
    price: 3194.8,
    percent: -0.25,
    isDown: true,
  },
  {
    id: 4,
    name: "KPITTECH",
    exchange: "NSE",
    price: 266.45,
    percent: 3.54,
    isDown: false,
  },
  {
    id: 5,
    name: "QUICKHEAL",
    exchange: "NSE",
    price: 308.55,
    percent: -0.15,
    isDown: true,
  },
  {
    id: 6,
    name: "WIPRO",
    exchange: "NSE",
    price: 577.75,
    percent: 0.32,
    isDown: false,
  },
  {
    id: 7,
    name: "M&M",
    exchange: "NSE",
    price: 779.8,
    percent: -0.01,
    isDown: true,
  },
  {
    id: 8,
    name: "RELIANCE",
    exchange: "NSE",
    price: 2112.4,
    percent: 1.44,
    isDown: false,
  },
  {
    id: 9,
    name: "HUL",
    exchange: "NSE",
    price: 512.4,
    percent: 1.04,
    isDown: false,
  },
];